-- Create Reviews Table
-- Author: Vehicle Reviews Enhancement
-- Date: February 14, 2026
-- Purpose: Store vehicle reviews and ratings from customers

-- Create review table
CREATE TABLE IF NOT EXISTS public.review
(
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_rating integer NOT NULL CHECK (review_rating >= 1 AND review_rating <= 5),
    review_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create index on inv_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_review_inv_id ON public.review(inv_id);

-- Create index on account_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_review_account_id ON public.review(account_id);
